query tokens($cursor: String) {
  tokens(after: $cursor, orderBy: "timestamp", orderDirection: "desc") {
    items {
      collection {
        id
        creatorAddress
      }
      tokenId
      name
      image
    }
    pageInfo {
      endCursor
    }
  }
}
