query mints($token: String!, $cursor: String) {
  token(id: $token) {
    mintCount
  }
  mints(
    where: { tokenId: $token }
    after: $cursor
    orderBy: "timestamp"
    orderDirection: "desc"
  ) {
    items {
      id
      timestamp
      minterAddress
      amount
      comment
    }
    pageInfo {
      endCursor
    }
  }
}
