query collections($address: String!) {
  collections(
    where: { creatorAddress: $address }
    orderBy: "timestamp"
    orderDirection: "desc"
    limit: 1000
  ) {
    items {
      id
      name
      image
      tokenCount
    }
  }
}
