query token($token: String!) {
  token(id: $token) {
    collection {
      id
      creatorAddress
      name
      description
      image
    }
    tokenId
    timestamp
    name
    description
    image
    price
    maxSupply
    endTimestamp
  }
}
