name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-test:
    name: Lint and test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          submodules: recursive
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm typecheck
